### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wi1dna** [Drixevel/Chat-Processor#11]
when I'm the one on the server, I can see your posts. when comes to another person, then I see his message as he was mine, but I do not see her as he did. no errors in the logs.

**Comment by shanapu** [comment]
same here: https://forums.alliedmods.net/showpost.php?p=2484365&postcount=112

>  I used an older version of chat-processor (<2.0) on MyJailbreak which worked fine. 
> After update to latest chat-processor a bug occurs on CSGO/SM1.8. But i don't get any of the errors mentions above. 
> If there is only one player on server chat reacts normal. If there is more than one player, the author of the chat message will not receive his own message.
> 
> This also happen with test-messages.sp. 
> One client on server -> author = recipients
> More than one client on server -> author is missing from recipients

**Comment by wi1dna** [comment]
soo bad, nned 1.8+

**Comment by shanapu** [comment]
seems fixed here: https://github.com/Drixevel/Chat-Processor/pull/12
