### ISSUE TITLE
2 end chat

### ISSUE THREAD

**Issue by mrkos9i4ok** [Drixevel/Chat-Processor#3]
![20160916230429_1](https://cloud.githubusercontent.com/assets/20227450/18599762/a97b00c8-7c62-11e6-943a-288d4673b6d9.jpg)
![20160916230433_1](https://cloud.githubusercontent.com/assets/20227450/18599763/a97caf68-7c62-11e6-9073-d81f417eb863.jpg)
Error
At the end of the text 2 are always added

**Comment by Bara20** [comment]
[Remove test-messages.smx](https://github.com/Drixevel/Chat-Processor/blob/master/scripting/test-messages.sp#L27)

**Comment by mrkos9i4ok** [comment]
Sorry,i am stupid)
