### ISSUE TITLE
[BUG] Chat Specs

### ISSUE THREAD

**Issue by crashzk** [Drixevel/Chat-Processor#36]
The specs can talk to the live players of CT or T at any time follows an example print:
![screenshot_1](https://user-images.githubusercontent.com/32937653/39959691-c8e64918-55eb-11e8-9998-ee67c894c36d.png)

No error in the logs apparently: 
[errors_20180512.log](https://github.com/ShadersAllen/Chat-Processor/files/1997770/errors_20180512.log)

**Comment by paulocrash** [comment]
Any news on this BUG, any fixes?

In any case even if I configure CVAR `sm_chatprocessor_deadchat` the problem does not solve

**Comment by estiawan** [comment]
any fix for it?

**Comment by crashzk** [comment]
```
sm_chatprocessor_deadchat "1"    // Controls how dead communicate. (0 = off, 1 = on)
sm_chatprocessor_allchat "0"    // Allows both teams to communicate with each other through team chat. (0 = off, 1 = on)
```

Did you try to change those cvars? See if it solves your problem.
