### ISSUE TITLE
CP_OnChatMessage not emitting on say_team

### ISSUE THREAD

**Issue by T1MOXA** [Drixevel/Chat-Processor#52]
Code:
```sp
#include <chat-processor>

public Action CP_OnChatMessage(int &iClient, ArrayList hRecipients, char[] sFlags, char[] sName, char[] sMessage, bool& bProcesscolors, bool& bRemovecolors) {
	PrintToServer("CP_OnChatMessage: %s || %s", sFlags, sMessage);
	return Plugin_Continue;
}
```

Plugin version - 2.2.0
SourceMod Version: 1.10.0.6416

**Comment by Drixevel** [comment]
I'm assuming you solved the issue by closing this issue but depending on the game, you should able to find and/or add different types of messages with the configuration file. (just in case that was your issue)

Cheers.

**Comment by T1MOXA** [comment]
Yes, I solved the problem, or rather it solved itself.
Thanks for the reply.
