### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hartmanziga** [Drixevel/Chat-Processor#69]
L 07/13/2020 - 13:32:04: [SM] Exception reported: Invalid field "params" for message "CCSUsrMsg_SayText2"
L 07/13/2020 - 13:32:04: [SM] Blaming: simple-chatprocessor.smx
L 07/13/2020 - 13:32:04: [SM] Call stack trace:
L 07/13/2020 - 13:32:04: [SM]   [0] PbReadString
L 07/13/2020 - 13:32:04: [SM]   [1] Line 353, D:\Libraries\Documents\Repos\Simple Chat Processor\scripting\simple-chatprocessor.sp::OnSayText2

**Comment by Drixevel** [comment]
This plugin is not related to this repository.
