### ISSUE TITLE
Team chat colors missing

### ISSUE THREAD

**Issue by yuv41** [Drixevel/Chat-Processor#71]
Basically this is what the chat is looking like without chat processor >
![img](https://img.shibe.host/DIFu4/yuFECAgE46.png/raw)
And this is with chat processor enabled > 
![img](https://img.shibe.host/DIFu4/TetEpAKU17.png/raw)
A fix or support will be appreciated

**Comment by KondiU** [comment]
can you reupload the images? I think I have the same problem but the links expired so I can't check
